# These are supported funding model platforms

github: # Opcional, si activas GitHub Sponsors
patreon: 
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
buy_me_a_coffee: 
thanks_dev: 
custom: ["https://paypal.me/ExoPaso?locale.x=es_XC&country.x=DO"]

